export const PLAYER = 'player'
export const QUEST_GIVER = 'quest_giver'

export const QUEST_GIVER_NEW_QUEST = '0'
export const QUEST_GIVER_INCOMPLETE_QUEST = '1'
export const QUEST_GIVER_COMPLETE_QUEST = '2'
export const QUEST_GIVER_NO_QUEST = '3'

export const PLAYER_WALK_DOWN = 'player_walk_down'
export const PLAYER_WALK_UP = 'player_walk_up'
export const PLAYER_WALK_LEFT = 'player_walk_left'
export const PLAYER_WALK_RIGHT = 'player_walk_right'

export const GIRAFFE = 'giraffe'
export const TIGER = 'tiger'
export const ELEPHANT = 'elephant'
export const LION = 'lion'
export const ZEBRA = 'zebra'

export const STAR_FULL = 'STAR_FULL'
export const STAR_EMPTY = 'STAR_EMPTY'

export const ELEPHANT_QUEST_AUDIO = 'Elephant-quest.mp3'
export const ZEBRA_QUEST_AUDIO = 'Zebra-quest.mp3'
export const GIRAFFE_QUEST_AUDIO = 'Giraffe-quest.mp3'
export const TIGER_QUEST_AUDIO = 'Tiger-quest.mp3'
export const LION_QUEST_AUDIO = 'Lion-quest.mp3'
export const LEVEL1_COMPLETE_AUDIO = 'Level1-complete.mp3'
export const LEVEL1_WELCOME_AUDIO = 'Level1-welcome.mp3'
export const ELEPHANT_VOICE_AUDIO = 'Elephant-voice.mp3'
export const ZEBRA_VOICE_AUDIO = 'Zebra-voice.mp3'
export const GIRAFFE_VOICE_AUDIO = 'Giraffe-voice.mp3'
export const TIGER_VOICE_AUDIO = 'Tiger-voice.mp3'
export const LION_VOICE_AUDIO = 'Lion-voice.mp3'
